2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Configure stats pid to 3286766
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Loading settings from /home/rinya/.config/wandb/settings
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Loading settings from /home/rinya/ZOLLMFT/ZO_LLM/wandb/settings
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'disabled': 'false', 'project': 'zo-llm-ft', 'api_key': '***REDACTED***'}
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'run.py', 'program_abspath': '/home/rinya/ZOLLMFT/ZO_LLM/run.py', 'program': '/home/rinya/ZOLLMFT/ZO_LLM/run.py'}
2025-07-24 17:23:14,916 INFO    MainThread:3286766 [wandb_init.py:_log_setup():524] Logging user logs to /home/rinya/ZOLLMFT/ZO_LLM/wandb/run-20250724_172314-dcr1o2zi/logs/debug.log
2025-07-24 17:23:14,917 INFO    MainThread:3286766 [wandb_init.py:_log_setup():525] Logging internal logs to /home/rinya/ZOLLMFT/ZO_LLM/wandb/run-20250724_172314-dcr1o2zi/logs/debug-internal.log
2025-07-24 17:23:14,917 INFO    MainThread:3286766 [wandb_init.py:init():564] calling init triggers
2025-07-24 17:23:14,917 INFO    MainThread:3286766 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2025-07-24 17:23:14,917 INFO    MainThread:3286766 [wandb_init.py:init():614] starting backend
2025-07-24 17:23:14,917 INFO    MainThread:3286766 [wandb_init.py:init():618] setting up manager
2025-07-24 17:23:14,918 INFO    MainThread:3286766 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-07-24 17:23:14,925 INFO    MainThread:3286766 [wandb_init.py:init():624] backend started and connected
2025-07-24 17:23:14,937 INFO    MainThread:3286766 [wandb_init.py:init():716] updated telemetry
2025-07-24 17:23:14,954 INFO    MainThread:3286766 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2025-07-24 17:23:15,285 ERROR   MainThread:3286766 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-07-24 17:23:15,424 ERROR   MainThread:3286766 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
Traceback (most recent call last):
  File "/home/rinya/anaconda3/envs/zollm2/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
  File "/home/rinya/anaconda3/envs/zollm2/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
2025-07-24 17:23:16,441 WARNING MsgRouterThr:3286766 [router.py:message_loop():77] message_loop has been closed
